export const gameSettings = {
    gameID: 'game',
    animationMS: 30,
    //player1Colour: 'yellow',
    //player2Colour: 'green',
    ballColour: 'white',
    ballNumberInitial: 1,
    ballSpeed: 1,
    initialBallVX: 1,
    initialBallVY: 1,
    paddleWidth: 5,
    paddleHeight: 50,
    paddleSpeed: 5,
    paddleColourInitial: 0,
    paddleColours: ['blue','green','yellow','orange','red'],
};